
export const GET_ALL_DRONE_STRIKES = 'GET_ALL_DRONE_STRIKES';
export const GET_SPECIFIC_DRONE_STRIKE = 'GET_SPECIFIC_DRONE_STRIKE';

export const SET_DRONE_CHART_DEATHS = 'SET_DRONE_CHART_DEATHS';
export const SET_DRONE_CHART_DEATHS_CIVILIANS = 'SET_DRONE_CHART_DEATHS_CIVILIANS';
export const SET_DRONE_CHART_DEATHS_CHILDREN = 'SET_DRONE_CHART_DEATHS_CHILDREN';
export const SET_DRONE_CHART_DEATHS_PIE_DATA = 'SET_DRONE_CHART_DEATHS_PIE_DATA';

export const GET_LOADING_STATUS = 'GET_LOADING_STATUS';
export const GET_ERROR_STATUS = 'GET_ERROR_STATUS';